export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POST = 'FETCH_POST';
export const FETCH_PAGES = 'FETCH_PAGES';
export const FETCH_PAGE = 'FETCH_PAGE';
export const OPEN_NAVIGATION = 'OPEN_NAVIGATION';
export const CLOSE_NAVIGATION = 'CLOSE_NAVIGATION';
